[2024-10-06T18:12:47.793+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T18:12:47.849+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T18:12:47.887+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T18:12:47.887+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T18:12:47.943+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-23 00:00:00+00:00
[2024-10-06T18:12:47.965+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=672) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T18:12:47.980+0000] {standard_task_runner.py:72} INFO - Started process 700 to run task
[2024-10-06T18:12:47.989+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpw683kd66']
[2024-10-06T18:12:47.998+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T18:12:48.151+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T18:12:48.365+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-10-06T18:12:48.370+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T18:12:48.439+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T18:12:48.449+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_to_redshift.py", line 11, in load_data_to_redshift
    start_date=context['data_interval_start']
              ^^^^^^^
NameError: name 'context' is not defined
[2024-10-06T18:12:48.532+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20241006T181247, end_date=20241006T181248
[2024-10-06T18:12:48.594+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T18:12:48.599+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 41 for task obtener_y_preparar_cotizaciones (name 'context' is not defined; 700)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_to_redshift.py", line 11, in load_data_to_redshift
    start_date=context['data_interval_start']
              ^^^^^^^
NameError: name 'context' is not defined
[2024-10-06T18:12:48.663+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-06T18:12:48.702+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T18:12:48.705+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:34:04.099+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:34:04.191+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T20:34:04.231+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T20:34:04.235+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:34:04.315+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-23 00:00:00+00:00
[2024-10-06T20:34:04.364+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2047) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:34:04.376+0000] {standard_task_runner.py:72} INFO - Started process 2086 to run task
[2024-10-06T20:34:04.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmprrpql5dw']
[2024-10-06T20:34:04.399+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:34:04.641+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:34:04.871+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-10-06T20:34:04.879+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:34:04.949+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:34:04.949+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:34:06.289+0000] {logging_mixin.py:190} INFO - 2024-09-23
[2024-10-06T20:34:06.291+0000] {logging_mixin.py:190} INFO - 2024-09-24
[2024-10-06T20:34:06.295+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:06.295+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:06.296+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:06.296+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:06.298+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:07.808+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:07.817+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:34:07.814+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:07.814+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:07.824+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:07.827+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:34:07.847+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:34:09.306+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:34:09.344+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:34:09.344+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20241006T203404, end_date=20241006T203409
[2024-10-06T20:34:09.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:34:09.401+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:34:09.402+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-06T20:34:09.403+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:35:45.624+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:35:45.684+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T20:35:45.718+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T20:35:45.725+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:35:45.857+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-23 00:00:00+00:00
[2024-10-06T20:35:45.868+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2428) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:35:45.880+0000] {standard_task_runner.py:72} INFO - Started process 2463 to run task
[2024-10-06T20:35:45.898+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp2h_dlhu1']
[2024-10-06T20:35:45.915+0000] {standard_task_runner.py:105} INFO - Job 148: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:35:46.111+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:35:46.493+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-10-06T20:35:46.502+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:35:46.711+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:35:46.714+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:35:48.650+0000] {logging_mixin.py:190} INFO - 2024-09-23
[2024-10-06T20:35:48.682+0000] {logging_mixin.py:190} INFO - 2024-09-24
[2024-10-06T20:35:48.706+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:48.738+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:50.376+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:35:50.382+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:35:50.415+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:35:50.422+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:35:50.428+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:35:50.433+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:35:50.443+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:35:51.358+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:35:51.373+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:35:51.374+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20241006T203545, end_date=20241006T203551
[2024-10-06T20:35:51.434+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:35:51.446+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:35:51.447+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:42:51.164+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:42:51.240+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T20:42:51.266+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T20:42:51.268+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:42:51.348+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-23 00:00:00+00:00
[2024-10-06T20:42:51.409+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp6vsrax6o']
[2024-10-06T20:42:51.416+0000] {standard_task_runner.py:105} INFO - Job 183: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:42:51.407+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2878) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:42:51.432+0000] {standard_task_runner.py:72} INFO - Started process 2919 to run task
[2024-10-06T20:42:51.838+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:42:52.003+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-10-06T20:42:52.018+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:42:52.080+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:42:52.083+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:42:53.903+0000] {logging_mixin.py:190} INFO - 2024-09-23
[2024-10-06T20:42:53.904+0000] {logging_mixin.py:190} INFO - 2024-09-24
[2024-10-06T20:42:53.909+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:53.910+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:53.916+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:55.141+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:42:55.142+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:42:55.158+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:42:55.189+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:42:55.307+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:42:55.310+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:42:55.323+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:42:56.104+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:42:56.125+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:42:56.125+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20241006T204251, end_date=20241006T204256
[2024-10-06T20:42:56.175+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:42:56.221+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:42:56.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:02:14.363+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:02:14.417+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T21:02:14.435+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T21:02:14.436+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:02:14.560+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-23 00:00:00+00:00
[2024-10-06T21:02:14.589+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3568) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:02:14.593+0000] {standard_task_runner.py:72} INFO - Started process 3628 to run task
[2024-10-06T21:02:14.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpsg9ry9az']
[2024-10-06T21:02:14.620+0000] {standard_task_runner.py:105} INFO - Job 228: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:02:14.892+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:02:15.191+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-10-06T21:02:15.193+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:02:15.224+0000] {logging_mixin.py:190} INFO - 2024-09-23
[2024-10-06T21:02:15.225+0000] {logging_mixin.py:190} INFO - 2024-09-24
[2024-10-06T21:02:15.242+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:15.244+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:15.247+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:15.247+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:15.247+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:15.247+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:15.259+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:16.789+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:16.807+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:16.814+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:16.816+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:16.984+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T21:02:16.984+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:02:16.994+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:02:17.009+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:02:17.009+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:02:23.003+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T21:02:23.031+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:02:23.032+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20241006T210214, end_date=20241006T210223
[2024-10-06T21:02:23.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T21:02:23.078+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:02:23.079+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:03:56.859+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:03:56.916+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T21:03:56.935+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [queued]>
[2024-10-06T21:03:56.940+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:03:57.095+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-23 00:00:00+00:00
[2024-10-06T21:03:57.126+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3947) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:03:57.136+0000] {standard_task_runner.py:72} INFO - Started process 4013 to run task
[2024-10-06T21:03:57.123+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-23T00:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpm2oek6kd']
[2024-10-06T21:03:57.143+0000] {standard_task_runner.py:105} INFO - Job 263: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:03:57.306+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-23T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:03:57.626+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-23T00:00:00+00:00'
[2024-10-06T21:03:57.637+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:03:57.656+0000] {logging_mixin.py:190} INFO - 2024-09-23
[2024-10-06T21:03:57.657+0000] {logging_mixin.py:190} INFO - 2024-09-24
[2024-10-06T21:03:57.670+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:57.672+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:57.672+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:59.034+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:03:59.054+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T21:03:59.062+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T21:03:59.075+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T21:03:59.075+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T21:03:59.075+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:03:59.081+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:03:59.091+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:03:59.091+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:04:01.025+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T21:04:01.041+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:04:01.041+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-23T00:00:00+00:00, execution_date=20240923T000000, start_date=20241006T210356, end_date=20241006T210401
[2024-10-06T21:04:01.093+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T21:04:01.121+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:04:01.124+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
