[2024-10-26T16:33:38.133+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:33:38.143+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T16:33:38.148+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T16:33:38.148+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:33:38.155+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T16:33:38.159+0000] {standard_task_runner.py:72} INFO - Started process 220 to run task
[2024-10-26T16:33:38.162+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp_mbgmp31']
[2024-10-26T16:33:38.164+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:33:38.204+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:33:38.243+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T16:33:38.247+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:33:38.256+0000] {logging_mixin.py:190} INFO - 2024-09-09
[2024-10-26T16:33:38.256+0000] {logging_mixin.py:190} INFO - 2024-09-10
[2024-10-26T16:33:39.020+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:39.021+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:39.030+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:39.035+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:39.037+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:39.038+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:33:39.081+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:33:41.212+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:33:41.255+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:33:41.256+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T163338, end_date=20241026T163341
[2024-10-26T16:33:41.336+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:33:41.441+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:33:41.453+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T16:36:31.195+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:36:31.204+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T16:36:31.208+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T16:36:31.208+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:36:31.214+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T16:36:31.218+0000] {standard_task_runner.py:72} INFO - Started process 1272 to run task
[2024-10-26T16:36:31.222+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpjb8bd92b']
[2024-10-26T16:36:31.224+0000] {standard_task_runner.py:105} INFO - Job 188: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:36:31.260+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:36:31.308+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T16:36:31.309+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:36:31.316+0000] {logging_mixin.py:190} INFO - 2024-09-09
[2024-10-26T16:36:31.316+0000] {logging_mixin.py:190} INFO - 2024-09-10
[2024-10-26T16:36:32.017+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:32.038+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:32.065+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:32.158+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T16:36:32.158+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:36:32.172+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:36:32.207+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:36:34.236+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:36:34.287+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:36:34.287+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T163631, end_date=20241026T163634
[2024-10-26T16:36:34.367+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:36:34.415+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:36:34.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T18:55:31.299+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T18:55:31.316+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T18:55:31.325+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T18:55:31.326+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T18:55:31.345+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T18:55:31.355+0000] {standard_task_runner.py:72} INFO - Started process 174 to run task
[2024-10-26T18:55:31.363+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp9mf5xdln']
[2024-10-26T18:55:31.366+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T18:55:31.427+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host 0c643dd08f0d
[2024-10-26T18:55:31.515+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T18:55:31.519+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T18:55:31.528+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-09 a 2024-09-10
[2024-10-26T18:55:31.530+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:31.539+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T185531, end_date=20241026T185531
[2024-10-26T18:55:31.547+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T18:55:31.548+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'config/config.json'; 174)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:31.585+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T18:55:31.611+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T18:55:31.616+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:03:24.587+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:03:24.626+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:03:24.637+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:03:24.637+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:03:24.650+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T19:03:24.661+0000] {standard_task_runner.py:72} INFO - Started process 160 to run task
[2024-10-26T19:03:24.667+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpi79fjxx5']
[2024-10-26T19:03:24.673+0000] {standard_task_runner.py:105} INFO - Job 138: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:03:24.765+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host 22d081b4f909
[2024-10-26T19:03:24.867+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T19:03:24.868+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:03:24.878+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-09 a 2024-09-10
[2024-10-26T19:03:24.878+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:24.889+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T190324, end_date=20241026T190324
[2024-10-26T19:03:24.905+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:03:24.907+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 138 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 160)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:24.935+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:03:24.952+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:03:24.955+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:08:33.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:08:33.720+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:08:33.730+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:08:33.733+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:08:33.752+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T19:08:33.760+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2024-10-26T19:08:33.765+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpee29ofem']
[2024-10-26T19:08:33.768+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:08:33.839+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host f4cb477e9eef
[2024-10-26T19:08:33.944+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T19:08:33.946+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:08:33.959+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-09 a 2024-09-10
[2024-10-26T19:08:33.961+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:08:33.979+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T190833, end_date=20241026T190833
[2024-10-26T19:08:33.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:08:33.990+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:08:34.031+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:08:34.049+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:08:34.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:12:34.599+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:12:34.610+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:12:34.616+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:12:34.617+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:12:34.626+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T19:12:34.631+0000] {standard_task_runner.py:72} INFO - Started process 203 to run task
[2024-10-26T19:12:34.643+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpfp_alizr']
[2024-10-26T19:12:34.657+0000] {standard_task_runner.py:105} INFO - Job 135: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:12:34.711+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host 2e7a74dc0e24
[2024-10-26T19:12:34.792+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T19:12:34.794+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:12:34.812+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-09 a 2024-09-10
[2024-10-26T19:12:34.817+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:12:35.521+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:35.561+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:12:35.537+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:35.529+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:35.574+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:12:35.582+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:12:35.623+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:12:35.636+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:12:35.663+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:12:37.030+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:12:37.034+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:12:37.739+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:12:37.743+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:12:37.767+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:12:37.794+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:12:37.841+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:12:37.846+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T191234, end_date=20241026T191237
[2024-10-26T19:12:37.933+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:12:38.013+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:12:38.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:16:12.566+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:16:12.582+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:16:12.586+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [queued]>
[2024-10-26T19:16:12.587+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:16:12.593+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-09 00:00:00+00:00
[2024-10-26T19:16:12.597+0000] {standard_task_runner.py:72} INFO - Started process 182 to run task
[2024-10-26T19:16:12.614+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-09T00:00:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp_41y2nln']
[2024-10-26T19:16:12.621+0000] {standard_task_runner.py:105} INFO - Job 303: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:16:12.673+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-09T00:00:00+00:00 [running]> on host 3ba590fe69c6
[2024-10-26T19:16:12.726+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-09T00:00:00+00:00'
[2024-10-26T19:16:12.727+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:16:12.738+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-09 a 2024-09-10
[2024-10-26T19:16:12.739+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:16:13.516+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:13.529+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T19:16:13.603+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:16:13.604+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:16:13.629+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:16:13.629+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:16:13.649+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:16:13.652+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:16:13.678+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:16:15.930+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:16:15.963+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:16:16.978+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:16:16.985+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:16:16.997+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:16:16.999+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:16:17.059+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:16:17.062+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-09T00:00:00+00:00, execution_date=20240909T000000, start_date=20241026T191612, end_date=20241026T191617
[2024-10-26T19:16:17.212+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:16:17.258+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
