[2024-10-26T16:34:13.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:34:13.410+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T16:34:13.422+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T16:34:13.424+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:34:13.450+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T16:34:13.462+0000] {standard_task_runner.py:72} INFO - Started process 770 to run task
[2024-10-26T16:34:13.470+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpwhs8b4bw']
[2024-10-26T16:34:13.479+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:34:13.614+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:34:13.757+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T16:34:13.762+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:34:13.786+0000] {logging_mixin.py:190} INFO - 2024-10-07
[2024-10-26T16:34:13.796+0000] {logging_mixin.py:190} INFO - 2024-10-08
[2024-10-26T16:34:14.690+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:14.710+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:14.719+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:14.728+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:14.730+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:34:14.730+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:34:14.763+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:34:16.693+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:34:16.736+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:34:16.743+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T163413, end_date=20241026T163416
[2024-10-26T16:34:16.877+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:34:16.940+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:34:16.954+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T16:37:08.963+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:37:08.989+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T16:37:09.003+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T16:37:09.005+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:37:09.040+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T16:37:09.063+0000] {standard_task_runner.py:72} INFO - Started process 1809 to run task
[2024-10-26T16:37:09.072+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp3hq2ktmp']
[2024-10-26T16:37:09.085+0000] {standard_task_runner.py:105} INFO - Job 275: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:37:09.159+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:37:09.282+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T16:37:09.289+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:37:09.313+0000] {logging_mixin.py:190} INFO - 2024-10-07
[2024-10-26T16:37:09.315+0000] {logging_mixin.py:190} INFO - 2024-10-08
[2024-10-26T16:37:09.983+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:37:09.988+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:37:09.998+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:37:10.014+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T16:37:10.024+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:37:10.024+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:37:10.038+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:37:12.147+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:37:12.312+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:37:12.314+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T163708, end_date=20241026T163712
[2024-10-26T16:37:12.427+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:37:12.479+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T18:55:55.385+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T18:55:55.407+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T18:55:55.422+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T18:55:55.423+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T18:55:55.459+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T18:55:55.475+0000] {standard_task_runner.py:72} INFO - Started process 411 to run task
[2024-10-26T18:55:55.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp_oxwn2_t']
[2024-10-26T18:55:55.491+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T18:55:55.557+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host 0c643dd08f0d
[2024-10-26T18:55:55.704+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T18:55:55.706+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T18:55:55.733+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-07 a 2024-10-08
[2024-10-26T18:55:55.736+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:55.764+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T185555, end_date=20241026T185555
[2024-10-26T18:55:55.778+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T18:55:55.781+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 80 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'config/config.json'; 411)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:55.841+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T18:55:55.866+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:03:55.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:03:55.301+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:03:55.308+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:03:55.309+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:03:55.317+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T19:03:55.326+0000] {standard_task_runner.py:72} INFO - Started process 389 to run task
[2024-10-26T19:03:55.330+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpdj0wo_7w']
[2024-10-26T19:03:55.339+0000] {standard_task_runner.py:105} INFO - Job 193: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:03:55.404+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host 22d081b4f909
[2024-10-26T19:03:55.456+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T19:03:55.458+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:03:55.471+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-07 a 2024-10-08
[2024-10-26T19:03:55.472+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:55.481+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T190355, end_date=20241026T190355
[2024-10-26T19:03:55.492+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:03:55.493+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 193 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:55.516+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:03:55.530+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:03:55.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:09:11.811+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:09:11.841+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:09:11.851+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:09:11.853+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:09:11.876+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T19:09:11.891+0000] {standard_task_runner.py:72} INFO - Started process 391 to run task
[2024-10-26T19:09:11.898+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp5twg5lib']
[2024-10-26T19:09:11.922+0000] {standard_task_runner.py:105} INFO - Job 78: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:09:12.018+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host f4cb477e9eef
[2024-10-26T19:09:12.223+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T19:09:12.227+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:09:12.253+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-07 a 2024-10-08
[2024-10-26T19:09:12.255+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:09:12.279+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T190911, end_date=20241026T190912
[2024-10-26T19:09:12.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:09:12.306+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 78 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 391)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:09:12.324+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:09:12.338+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:13:13.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:13:13.448+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:13:13.463+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:13:13.468+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:13:13.631+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T19:13:13.636+0000] {standard_task_runner.py:72} INFO - Started process 741 to run task
[2024-10-26T19:13:13.650+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpgynyoeky']
[2024-10-26T19:13:13.691+0000] {standard_task_runner.py:105} INFO - Job 225: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:13:13.857+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host 2e7a74dc0e24
[2024-10-26T19:13:14.166+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T19:13:14.169+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:13:14.202+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-07 a 2024-10-08
[2024-10-26T19:13:14.232+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:13:15.164+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:15.173+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:15.180+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:15.182+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:15.194+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:13:15.195+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:13:15.213+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:13:15.214+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:13:15.243+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:13:16.589+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:13:16.591+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:13:17.248+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:13:17.263+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:13:17.270+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:13:17.299+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:13:17.365+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:13:17.367+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T191313, end_date=20241026T191317
[2024-10-26T19:13:17.475+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:13:17.585+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:16:56.991+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:16:57.010+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:16:57.030+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [queued]>
[2024-10-26T19:16:57.031+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:16:57.074+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-07 00:00:00+00:00
[2024-10-26T19:16:57.081+0000] {standard_task_runner.py:72} INFO - Started process 722 to run task
[2024-10-26T19:16:57.088+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-07T00:00:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp3nwj9_zs']
[2024-10-26T19:16:57.109+0000] {standard_task_runner.py:105} INFO - Job 391: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:16:57.206+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-07T00:00:00+00:00 [running]> on host 3ba590fe69c6
[2024-10-26T19:16:57.330+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-07T00:00:00+00:00'
[2024-10-26T19:16:57.334+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:16:57.346+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-07 a 2024-10-08
[2024-10-26T19:16:57.355+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:16:58.356+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:58.356+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:58.381+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:16:58.447+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:16:58.461+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:16:58.471+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:16:58.485+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:16:58.487+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:16:58.501+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:16:59.915+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:16:59.922+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:17:00.978+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:17:00.980+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:17:00.981+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:17:00.982+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:17:01.002+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:17:01.003+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-07T00:00:00+00:00, execution_date=20241007T000000, start_date=20241026T191657, end_date=20241026T191701
[2024-10-26T19:17:01.074+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:17:01.156+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:17:01.161+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
