[2024-10-14T17:30:34.467+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T17:30:35.780+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-10-14T17:30:36.730+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-03T00:00:00+00:00 [queued]>
[2024-10-14T17:30:36.822+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T17:30:37.277+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ccl_to_redshift> on 2024-09-03 00:00:00+00:00
[2024-10-14T17:30:38.052+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_ccl', 'ccl_to_redshift', 'scheduled__2024-09-03T00:00:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/dag_ccl.py', '--cfg-path', '/tmp/tmpa6vkj5ow']
[2024-10-14T17:30:38.091+0000] {standard_task_runner.py:105} INFO - Job 291: Subtask ccl_to_redshift
[2024-10-14T17:30:37.958+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=19079) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T17:30:38.106+0000] {standard_task_runner.py:72} INFO - Started process 19123 to run task
[2024-10-14T17:30:41.986+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_ccl.ccl_to_redshift scheduled__2024-09-03T00:00:00+00:00 [running]> on host f03003374728
[2024-10-14T17:30:46.232+0000] {job.py:229} INFO - Heartbeat recovered after 18.26 seconds
[2024-10-14T17:31:10.777+0000] {job.py:229} INFO - Heartbeat recovered after 16.44 seconds
[2024-10-14T17:31:27.769+0000] {job.py:229} INFO - Heartbeat recovered after 17.41 seconds
[2024-10-14T17:31:42.072+0000] {job.py:229} INFO - Heartbeat recovered after 20.03 seconds
[2024-10-14T17:31:57.093+0000] {job.py:229} INFO - Heartbeat recovered after 15.95 seconds
[2024-10-14T17:32:13.918+0000] {job.py:229} INFO - Heartbeat recovered after 18.16 seconds
[2024-10-14T17:32:35.630+0000] {job.py:229} INFO - Heartbeat recovered after 12.57 seconds
[2024-10-14T17:32:57.524+0000] {job.py:229} INFO - Heartbeat recovered after 23.77 seconds
[2024-10-14T17:33:06.627+0000] {job.py:229} INFO - Heartbeat recovered after 13.76 seconds
[2024-10-14T17:33:17.998+0000] {job.py:229} INFO - Heartbeat recovered after 11.51 seconds
[2024-10-14T17:33:28.511+0000] {job.py:229} INFO - Heartbeat recovered after 10.66 seconds
[2024-10-14T17:33:34.982+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-10-14T17:33:36.330+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-14T17:33:37.779+0000] {process_utils.py:132} INFO - Sending 15 to group 19123. PIDs of all processes in the group: [19123]
[2024-10-14T17:33:39.178+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 19123
[2024-10-14T17:33:40.014+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=19123, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='17:30:37') (19123) terminated with exit code -15
[2024-10-14T17:33:41.922+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
