[2024-10-26T16:33:54.721+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:33:54.747+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T16:33:54.766+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T16:33:54.770+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:33:54.821+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T16:33:54.825+0000] {standard_task_runner.py:72} INFO - Started process 431 to run task
[2024-10-26T16:33:54.828+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp_5vy1eky']
[2024-10-26T16:33:54.838+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:33:54.919+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:33:55.127+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T16:33:55.128+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:33:55.164+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-26T16:33:55.169+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-26T16:33:55.936+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:55.950+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:55.992+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:33:55.994+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:33:56.002+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:33:56.003+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:33:56.132+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:33:58.237+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:33:58.249+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:33:58.249+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T163354, end_date=20241026T163358
[2024-10-26T16:33:58.282+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:33:58.323+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:33:58.325+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T16:36:47.994+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:36:48.013+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T16:36:48.025+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T16:36:48.027+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:36:48.051+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T16:36:48.062+0000] {standard_task_runner.py:72} INFO - Started process 1462 to run task
[2024-10-26T16:36:48.066+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpxjd4akof']
[2024-10-26T16:36:48.078+0000] {standard_task_runner.py:105} INFO - Job 221: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:36:48.214+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:36:48.393+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T16:36:48.396+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:36:48.420+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-26T16:36:48.423+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-26T16:36:49.359+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:49.361+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:49.363+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:49.365+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:49.370+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:36:49.370+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:36:49.425+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:36:51.636+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:36:51.686+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:36:51.691+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T163648, end_date=20241026T163651
[2024-10-26T16:36:51.938+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:36:52.050+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:36:52.072+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T18:55:39.304+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T18:55:39.322+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T18:55:39.330+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T18:55:39.334+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T18:55:39.366+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T18:55:39.396+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpt8d3t3ff']
[2024-10-26T18:55:39.399+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T18:55:39.388+0000] {standard_task_runner.py:72} INFO - Started process 257 to run task
[2024-10-26T18:55:39.501+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host 0c643dd08f0d
[2024-10-26T18:55:39.618+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T18:55:39.624+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T18:55:39.656+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-18 a 2024-09-19
[2024-10-26T18:55:39.659+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:39.687+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T185539, end_date=20241026T185539
[2024-10-26T18:55:39.731+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T18:55:39.737+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'config/config.json'; 257)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:39.777+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T18:55:39.826+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T18:55:39.832+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:03:38.702+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:03:38.718+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:03:38.729+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:03:38.730+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:03:38.759+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T19:03:38.774+0000] {standard_task_runner.py:72} INFO - Started process 241 to run task
[2024-10-26T19:03:38.783+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp4emqf7wf']
[2024-10-26T19:03:38.801+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:03:38.865+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host 22d081b4f909
[2024-10-26T19:03:38.958+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T19:03:38.965+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:03:38.980+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-18 a 2024-09-19
[2024-10-26T19:03:38.981+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:39.000+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T190338, end_date=20241026T190338
[2024-10-26T19:03:39.019+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:03:39.020+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 156 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 241)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:39.058+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:03:39.096+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:03:39.106+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:08:43.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:08:43.446+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:08:43.462+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:08:43.462+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:08:43.474+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T19:08:43.480+0000] {standard_task_runner.py:72} INFO - Started process 228 to run task
[2024-10-26T19:08:43.484+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpmdbq4_o6']
[2024-10-26T19:08:43.490+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:08:43.592+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f4cb477e9eef
[2024-10-26T19:08:43.691+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T19:08:43.694+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:08:43.704+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-18 a 2024-09-19
[2024-10-26T19:08:43.705+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:08:43.715+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T190843, end_date=20241026T190843
[2024-10-26T19:08:43.725+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:08:43.726+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 228)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:08:43.750+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:08:43.779+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:08:43.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:12:50.666+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:12:50.685+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:12:50.693+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:12:50.694+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:12:50.709+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T19:12:50.718+0000] {standard_task_runner.py:72} INFO - Started process 396 to run task
[2024-10-26T19:12:50.724+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpshfdfc__']
[2024-10-26T19:12:50.730+0000] {standard_task_runner.py:105} INFO - Job 171: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:12:50.839+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host 2e7a74dc0e24
[2024-10-26T19:12:50.986+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T19:12:50.990+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:12:51.000+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-18 a 2024-09-19
[2024-10-26T19:12:51.003+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:12:51.906+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:51.926+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:12:51.915+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:51.916+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:51.923+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:51.915+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:51.971+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:12:51.972+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:12:52.026+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:12:54.252+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:12:54.254+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:12:55.485+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:12:55.488+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:12:55.491+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:12:55.495+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:12:55.542+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:12:55.554+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T191250, end_date=20241026T191255
[2024-10-26T19:12:55.687+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:12:55.737+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-26T19:12:55.774+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:16:33.584+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:16:33.626+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:16:33.633+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-26T19:16:33.636+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:16:33.657+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-26T19:16:33.669+0000] {standard_task_runner.py:72} INFO - Started process 383 to run task
[2024-10-26T19:16:33.679+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '337', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmppig7wg1g']
[2024-10-26T19:16:33.696+0000] {standard_task_runner.py:105} INFO - Job 337: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:16:33.772+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host 3ba590fe69c6
[2024-10-26T19:16:33.922+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-26T19:16:33.926+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:16:33.950+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-18 a 2024-09-19
[2024-10-26T19:16:33.954+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:16:34.815+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:34.816+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:34.817+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:34.831+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:16:35.021+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:16:35.023+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:16:35.039+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:16:35.040+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:16:35.077+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:16:36.384+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:16:36.385+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:16:37.051+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:16:37.053+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:16:37.054+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:16:37.054+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:16:37.068+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:16:37.069+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241026T191633, end_date=20241026T191637
[2024-10-26T19:16:37.096+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:16:37.138+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:16:37.140+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
