[2024-10-06T18:12:45.238+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T18:12:45.324+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T18:12:45.353+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T18:12:45.356+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T18:12:45.405+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T18:12:45.424+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=661) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T18:12:45.427+0000] {standard_task_runner.py:72} INFO - Started process 678 to run task
[2024-10-06T18:12:45.432+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp0y_55qul']
[2024-10-06T18:12:45.437+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T18:12:45.536+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T18:12:45.744+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T18:12:45.746+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T18:12:45.799+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T18:12:45.803+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_to_redshift.py", line 11, in load_data_to_redshift
    start_date=context['data_interval_start']
              ^^^^^^^
NameError: name 'context' is not defined
[2024-10-06T18:12:45.859+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T181245, end_date=20241006T181245
[2024-10-06T18:12:45.967+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T18:12:45.971+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task obtener_y_preparar_cotizaciones (name 'context' is not defined; 678)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_to_redshift.py", line 11, in load_data_to_redshift
    start_date=context['data_interval_start']
              ^^^^^^^
NameError: name 'context' is not defined
[2024-10-06T18:12:46.122+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-06T18:12:46.208+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T18:12:46.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:34:03.159+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:34:03.242+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T20:34:03.267+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T20:34:03.268+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:34:03.357+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T20:34:03.380+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2037) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:34:03.385+0000] {standard_task_runner.py:72} INFO - Started process 2070 to run task
[2024-10-06T20:34:03.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpajl_uafh']
[2024-10-06T20:34:03.415+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:34:03.628+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:34:03.813+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T20:34:03.827+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:34:03.892+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:34:03.900+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:34:05.314+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-06T20:34:05.321+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-06T20:34:05.349+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:05.352+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:05.355+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:34:06.804+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:06.804+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:06.808+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:06.811+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:34:06.817+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:34:06.819+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:34:06.828+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:34:07.479+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:34:07.572+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:34:07.577+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T203403, end_date=20241006T203407
[2024-10-06T20:34:07.681+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:34:07.838+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:34:07.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:35:43.689+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:35:43.795+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T20:35:43.823+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T20:35:43.836+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:35:43.929+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T20:35:43.995+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpjqdhbxnh']
[2024-10-06T20:35:43.999+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:35:43.988+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2418) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:35:44.017+0000] {standard_task_runner.py:72} INFO - Started process 2443 to run task
[2024-10-06T20:35:44.205+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:35:44.494+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T20:35:44.496+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:35:44.642+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:35:44.653+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:35:46.680+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-06T20:35:46.689+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-06T20:35:46.705+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:46.709+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:46.706+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:48.417+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:35:48.420+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:35:48.437+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:35:48.725+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:35:48.767+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:35:48.775+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:35:48.844+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:35:49.693+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:35:49.732+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:35:49.734+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T203543, end_date=20241006T203549
[2024-10-06T20:35:49.834+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:35:49.868+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:35:49.870+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:42:49.369+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:42:49.402+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T20:42:49.415+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T20:42:49.416+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:42:49.440+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T20:42:49.449+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2868) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:42:49.451+0000] {standard_task_runner.py:72} INFO - Started process 2889 to run task
[2024-10-06T20:42:49.453+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmphqybdbtt']
[2024-10-06T20:42:49.466+0000] {standard_task_runner.py:105} INFO - Job 179: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:42:49.721+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:42:50.062+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T20:42:50.068+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:42:50.229+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:42:50.247+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:42:51.697+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-06T20:42:51.720+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-06T20:42:51.789+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:51.792+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:53.173+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:42:53.269+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T20:42:53.363+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:42:53.383+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:42:53.399+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:42:53.410+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:42:53.460+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:42:54.177+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:42:54.211+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:42:54.212+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T204249, end_date=20241006T204254
[2024-10-06T20:42:54.246+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:42:54.270+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:42:54.271+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:01:08.238+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:01:08.255+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T21:01:08.270+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T21:01:08.272+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:01:08.322+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T21:01:08.327+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3494) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:01:08.333+0000] {standard_task_runner.py:72} INFO - Started process 3500 to run task
[2024-10-06T21:01:08.335+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmph6z3oifq']
[2024-10-06T21:01:08.338+0000] {standard_task_runner.py:105} INFO - Job 218: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:01:08.389+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:01:08.472+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T21:01:08.474+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:01:08.485+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-06T21:01:08.485+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-06T21:01:08.488+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:01:08.489+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:01:09.781+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:01:09.790+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T21:01:09.804+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T21:01:09.818+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T21:01:09.840+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T21:01:09.840+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:01:09.846+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:01:09.857+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:01:09.857+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:01:15.546+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stocks_to_redshift.py", line 13, in stocks_to_redshift
    load_data_to_redshift(df, table_name)
  File "/opt/airflow/dags/load_data_to_redshift.py", line 26, in load_data_to_redshift
    psycopg2.extras.execute_values(cur, query, data)
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "2024_felipe_miguel_reto_schema.otra_tabla" does not exist

[2024-10-06T21:01:15.589+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T210108, end_date=20241006T210115
[2024-10-06T21:01:15.607+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:01:15.608+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 218 for task obtener_y_preparar_cotizaciones (relation "2024_felipe_miguel_reto_schema.otra_tabla" does not exist
; 3500)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stocks_to_redshift.py", line 13, in stocks_to_redshift
    load_data_to_redshift(df, table_name)
  File "/opt/airflow/dags/load_data_to_redshift.py", line 26, in load_data_to_redshift
    psycopg2.extras.execute_values(cur, query, data)
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedTable: relation "2024_felipe_miguel_reto_schema.otra_tabla" does not exist

[2024-10-06T21:01:15.624+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-06T21:01:15.663+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:01:15.665+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:02:11.988+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:02:12.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T21:02:12.103+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T21:02:12.133+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:02:12.275+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T21:02:12.329+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3557) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:02:12.363+0000] {standard_task_runner.py:72} INFO - Started process 3578 to run task
[2024-10-06T21:02:12.354+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp8sis4zpi']
[2024-10-06T21:02:12.423+0000] {standard_task_runner.py:105} INFO - Job 223: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:02:12.626+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:02:12.878+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T21:02:12.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:02:12.921+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-06T21:02:12.922+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-06T21:02:12.953+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:12.955+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:02:14.773+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:14.796+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T21:02:14.783+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:14.774+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:02:14.797+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T21:02:14.823+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:02:14.891+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:02:14.985+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:02:14.992+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:02:21.584+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T21:02:21.610+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:02:21.610+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T210212, end_date=20241006T210221
[2024-10-06T21:02:21.673+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T21:02:21.689+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:02:21.690+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:03:55.039+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:03:55.102+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T21:03:55.130+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-06T21:03:55.136+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:03:55.183+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-06T21:03:55.204+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3937) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:03:55.208+0000] {standard_task_runner.py:72} INFO - Started process 3955 to run task
[2024-10-06T21:03:55.213+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmplx_qf0kf']
[2024-10-06T21:03:55.218+0000] {standard_task_runner.py:105} INFO - Job 258: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:03:55.371+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:03:55.624+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-06T21:03:55.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:03:55.646+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-06T21:03:55.648+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-06T21:03:55.660+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:55.663+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:57.377+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:03:57.380+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:03:57.385+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:03:57.583+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T21:03:57.646+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T21:03:57.649+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:03:57.721+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:03:57.821+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:03:57.827+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:03:59.868+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T21:03:59.905+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:03:59.905+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241006T210355, end_date=20241006T210359
[2024-10-06T21:03:59.963+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T21:04:00.025+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:04:00.027+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-15T18:16:02.213+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T18:16:02.252+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-15T18:16:02.260+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [queued]>
[2024-10-15T18:16:02.265+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-15T18:16:02.363+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-18 00:00:00+00:00
[2024-10-15T18:16:02.381+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=610) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T18:16:02.402+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-18T00:00:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp49r4ew17']
[2024-10-15T18:16:02.414+0000] {standard_task_runner.py:105} INFO - Job 342: Subtask obtener_y_preparar_cotizaciones
[2024-10-15T18:16:02.413+0000] {standard_task_runner.py:72} INFO - Started process 628 to run task
[2024-10-15T18:16:02.599+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-18T00:00:00+00:00 [running]> on host f03003374728
[2024-10-15T18:16:02.806+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-18T00:00:00+00:00'
[2024-10-15T18:16:02.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T18:16:02.831+0000] {logging_mixin.py:190} INFO - 2024-09-18
[2024-10-15T18:16:02.831+0000] {logging_mixin.py:190} INFO - 2024-09-19
[2024-10-15T18:16:02.838+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:16:02.839+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:16:02.840+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:16:04.427+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-15T18:16:04.431+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-15T18:16:04.433+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-15T18:16:04.433+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-15T18:16:04.896+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-15T18:16:04.881+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-15T18:16:04.968+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:15: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-15T18:16:05.092+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-15T18:16:05.093+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-15T18:16:07.112+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-15T18:16:07.161+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T18:16:07.163+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-18T00:00:00+00:00, execution_date=20240918T000000, start_date=20241015T181602, end_date=20241015T181607
[2024-10-15T18:16:07.235+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-15T18:16:07.301+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T18:16:07.309+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
