[2024-10-26T16:33:37.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:33:37.495+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T16:33:37.525+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T16:33:37.530+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:33:37.553+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T16:33:37.561+0000] {standard_task_runner.py:72} INFO - Started process 202 to run task
[2024-10-26T16:33:37.566+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpxkmw_n86']
[2024-10-26T16:33:37.571+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:33:37.699+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:33:37.774+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T16:33:37.777+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:33:37.787+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-26T16:33:37.789+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-26T16:33:38.486+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:38.490+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:33:38.491+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:33:38.492+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:33:38.493+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:33:38.495+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:33:38.497+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T16:33:38.497+0000] {multi.py:184} ERROR - ['PAMP.BA', 'AAPL.BA', 'CEPU.BA', 'BBAR.BA', 'TGNO4.BA', 'AMZN.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-26T16:33:38.542+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:33:39.901+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:33:39.908+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:33:39.909+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T163337, end_date=20241026T163339
[2024-10-26T16:33:39.957+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:33:39.991+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:33:39.994+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T16:36:29.810+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:36:29.826+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T16:36:29.841+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T16:36:29.842+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:36:29.862+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T16:36:29.881+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmptlq190nl']
[2024-10-26T16:36:29.885+0000] {standard_task_runner.py:105} INFO - Job 183: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:36:29.883+0000] {standard_task_runner.py:72} INFO - Started process 1242 to run task
[2024-10-26T16:36:29.953+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:36:30.045+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T16:36:30.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:36:30.058+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-26T16:36:30.060+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-26T16:36:30.696+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:30.703+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:36:30.706+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:36:30.711+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T16:36:30.728+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:36:30.735+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:36:30.737+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T16:36:30.738+0000] {multi.py:184} ERROR - ['PAMP.BA', 'AMZN.BA', 'BBAR.BA', 'TGNO4.BA', 'CEPU.BA', 'AAPL.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-26T16:36:30.761+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:36:32.145+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:36:32.164+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:36:32.165+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T163629, end_date=20241026T163632
[2024-10-26T16:36:32.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:36:32.274+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:36:32.276+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T18:55:30.506+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T18:55:30.549+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T18:55:30.592+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T18:55:30.593+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T18:55:30.635+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T18:55:30.647+0000] {standard_task_runner.py:72} INFO - Started process 163 to run task
[2024-10-26T18:55:30.656+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp2rpjp1rx']
[2024-10-26T18:55:30.664+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T18:55:30.800+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host 0c643dd08f0d
[2024-10-26T18:55:30.921+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T18:55:30.924+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T18:55:30.967+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-07 a 2024-09-08
[2024-10-26T18:55:30.994+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:31.032+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T185530, end_date=20241026T185531
[2024-10-26T18:55:31.064+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T18:55:31.068+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'config/config.json'; 163)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:31.137+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T18:55:31.169+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T18:55:31.184+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:03:23.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:03:23.236+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:03:23.330+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:03:23.334+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:03:23.361+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T19:03:23.373+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2024-10-26T19:03:23.387+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpq2usfs65']
[2024-10-26T19:03:23.398+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:03:23.507+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host 22d081b4f909
[2024-10-26T19:03:23.806+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T19:03:23.818+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:03:23.845+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-07 a 2024-09-08
[2024-10-26T19:03:23.851+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:23.905+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T190323, end_date=20241026T190323
[2024-10-26T19:03:23.998+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:03:24.011+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 133 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 144)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:03:24.024+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:03:24.054+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:08:32.848+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:08:32.904+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:08:32.981+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:08:32.985+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:08:33.016+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T19:08:33.037+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2024-10-26T19:08:33.052+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp2j5ie0zu']
[2024-10-26T19:08:33.070+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:08:33.222+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f4cb477e9eef
[2024-10-26T19:08:33.399+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T19:08:33.404+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:08:33.415+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-07 a 2024-09-08
[2024-10-26T19:08:33.417+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:08:33.432+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T190832, end_date=20241026T190833
[2024-10-26T19:08:33.444+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:08:33.445+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 144)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:08:33.481+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:08:33.510+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:08:33.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:12:32.964+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:12:32.996+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:12:33.010+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:12:33.012+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:12:33.032+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T19:12:33.049+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2024-10-26T19:12:33.062+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpfyeuh9rx']
[2024-10-26T19:12:33.070+0000] {standard_task_runner.py:105} INFO - Job 132: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:12:33.161+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host 2e7a74dc0e24
[2024-10-26T19:12:33.277+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T19:12:33.285+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:12:33.295+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-07 a 2024-09-08
[2024-10-26T19:12:33.299+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:12:34.319+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:12:34.337+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T19:12:34.373+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:12:34.394+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:12:34.670+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:12:34.671+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:12:34.671+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T19:12:34.673+0000] {multi.py:184} ERROR - ['PAMP.BA', 'CEPU.BA', 'AMZN.BA', 'TGNO4.BA', 'BBAR.BA', 'AAPL.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-26T19:12:34.690+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:12:34.691+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:12:34.700+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:12:36.928+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:12:36.932+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:12:36.948+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:12:36.958+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:12:36.970+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:12:36.975+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:12:36.996+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:12:36.998+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T191232, end_date=20241026T191236
[2024-10-26T19:12:37.104+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:12:37.211+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:12:37.232+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:16:11.314+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:16:11.337+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:16:11.352+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-26T19:16:11.353+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:16:11.389+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-26T19:16:11.399+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2024-10-26T19:16:11.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '299', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpfejq1vqz']
[2024-10-26T19:16:11.426+0000] {standard_task_runner.py:105} INFO - Job 299: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:16:11.517+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host 3ba590fe69c6
[2024-10-26T19:16:11.593+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-26T19:16:11.593+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:16:11.601+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-09-07 a 2024-09-08
[2024-10-26T19:16:11.601+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:16:12.275+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:16:12.295+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T19:16:12.302+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:16:12.373+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:16:12.374+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:16:12.381+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:16:12.383+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T19:16:12.385+0000] {multi.py:184} ERROR - ['AMZN.BA', 'TGNO4.BA', 'BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'PAMP.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-26T19:16:12.394+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:16:12.395+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:16:12.402+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:16:13.716+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:16:13.731+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:16:13.737+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:16:13.745+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:16:13.747+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:16:13.750+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:16:13.772+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:16:13.779+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241026T191611, end_date=20241026T191613
[2024-10-26T19:16:13.916+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:16:13.951+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
