[2024-10-06T18:07:33.040+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T18:07:33.105+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T18:07:33.138+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T18:07:33.139+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T18:07:33.217+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-06T18:07:33.256+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=474) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T18:07:33.263+0000] {standard_task_runner.py:72} INFO - Started process 506 to run task
[2024-10-06T18:07:33.265+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpy0v7bpe8']
[2024-10-06T18:07:33.274+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T18:07:33.467+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T18:07:33.725+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-06T18:07:33.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T18:07:33.794+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_to_redshift.py", line 9, in load_data_to_redshift
    engine =connect_to_redshift()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/connect_to_redshift.py", line 5, in connect_to_redshift
    with open('redshift_credentials.json','r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'redshift_credentials.json'
[2024-10-06T18:07:33.826+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241006T180733, end_date=20241006T180733
[2024-10-06T18:07:33.870+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T18:07:33.871+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'redshift_credentials.json'; 506)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_data_to_redshift.py", line 9, in load_data_to_redshift
    engine =connect_to_redshift()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/connect_to_redshift.py", line 5, in connect_to_redshift
    with open('redshift_credentials.json','r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'redshift_credentials.json'
[2024-10-06T18:07:33.901+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-06T18:07:33.948+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T18:07:33.966+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:33:51.261+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:33:51.357+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T20:33:51.381+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T20:33:51.382+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:33:51.461+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-06T20:33:51.468+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1887) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:33:51.473+0000] {standard_task_runner.py:72} INFO - Started process 1921 to run task
[2024-10-06T20:33:51.472+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp9owkco_f']
[2024-10-06T20:33:51.477+0000] {standard_task_runner.py:105} INFO - Job 96: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:33:51.815+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:33:52.186+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-06T20:33:52.207+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:33:52.279+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:33:52.283+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:33:54.296+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-06T20:33:54.348+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-06T20:33:54.370+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:33:54.394+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:33:56.027+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:33:56.028+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:33:56.038+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:33:56.068+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:33:56.095+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:33:56.103+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:33:56.104+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-06T20:33:56.104+0000] {multi.py:184} ERROR - ['AMZN.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'BBAR.BA', 'CEPU.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-06T20:33:56.117+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:33:56.125+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:33:56.136+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:33:56.137+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241006T203351, end_date=20241006T203356
[2024-10-06T20:33:56.162+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:33:56.184+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:33:56.185+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:35:25.890+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:35:25.947+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T20:35:25.956+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T20:35:25.959+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:35:25.987+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-06T20:35:26.000+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2266) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:35:26.002+0000] {standard_task_runner.py:72} INFO - Started process 2385 to run task
[2024-10-06T20:35:26.003+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp_xyyqd5j']
[2024-10-06T20:35:26.007+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:35:26.113+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:35:26.205+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-06T20:35:26.206+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:35:26.221+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:35:26.221+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:35:27.809+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-06T20:35:27.810+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-06T20:35:27.813+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:27.814+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:27.815+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:35:29.287+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:35:29.320+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T20:35:29.332+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T20:35:29.580+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:35:29.633+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T20:35:29.638+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:35:29.638+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-06T20:35:29.639+0000] {multi.py:184} ERROR - ['BBAR.BA', 'AAPL.BA', 'TGNO4.BA', 'CEPU.BA', 'PAMP.BA', 'AMZN.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-06T20:35:29.649+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:35:29.656+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:35:29.664+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:35:29.665+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241006T203525, end_date=20241006T203529
[2024-10-06T20:35:29.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:35:29.740+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:35:29.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T20:42:35.483+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T20:42:35.557+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T20:42:35.578+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T20:42:35.579+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T20:42:35.595+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-06T20:42:35.623+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2711) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T20:42:35.627+0000] {standard_task_runner.py:72} INFO - Started process 2786 to run task
[2024-10-06T20:42:35.629+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp9pwujbq1']
[2024-10-06T20:42:35.634+0000] {standard_task_runner.py:105} INFO - Job 168: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T20:42:35.711+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T20:42:35.830+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-06T20:42:35.833+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T20:42:35.870+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T20:42:35.873+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T20:42:37.225+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-06T20:42:37.229+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-06T20:42:37.237+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:37.240+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:37.241+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T20:42:38.689+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:42:38.691+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:42:38.692+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T20:42:38.709+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:42:38.709+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T20:42:38.714+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T20:42:38.715+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-06T20:42:38.715+0000] {multi.py:184} ERROR - ['TGNO4.BA', 'AMZN.BA', 'BBAR.BA', 'PAMP.BA', 'CEPU.BA', 'AAPL.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-06T20:42:38.732+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T20:42:38.742+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T20:42:38.757+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T20:42:38.757+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241006T204235, end_date=20241006T204238
[2024-10-06T20:42:38.804+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T20:42:38.827+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T20:42:38.829+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:00:53.053+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:00:53.134+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T21:00:53.172+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T21:00:53.175+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:00:53.234+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-06T21:00:53.441+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3344) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:00:53.458+0000] {standard_task_runner.py:72} INFO - Started process 3423 to run task
[2024-10-06T21:00:53.456+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp3ml20x32']
[2024-10-06T21:00:53.467+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:00:53.598+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:00:54.171+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-06T21:00:54.237+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:00:54.399+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-06T21:00:54.402+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-06T21:00:54.546+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:00:54.550+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:00:56.150+0000] {logging_mixin.py:190} WARNING - [                       0%                       ][                       0%                       ]
[2024-10-06T21:00:56.176+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-06T21:00:56.201+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T21:00:56.233+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T21:00:56.238+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:00:56.255+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-06T21:00:56.257+0000] {multi.py:184} ERROR - ['AMZN.BA', 'TGNO4.BA', 'PAMP.BA', 'AAPL.BA', 'CEPU.BA', 'BBAR.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-06T21:00:56.313+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:00:56.350+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:00:56.351+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:01:01.697+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T21:01:01.712+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:01:01.713+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241006T210053, end_date=20241006T210101
[2024-10-06T21:01:01.750+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T21:01:01.767+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:01:01.768+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-06T21:03:45.652+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T21:03:45.686+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T21:03:45.708+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-06T21:03:45.712+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-06T21:03:45.822+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-06T21:03:45.836+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3787) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T21:03:45.845+0000] {standard_task_runner.py:72} INFO - Started process 3845 to run task
[2024-10-06T21:03:45.845+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpmbqa7j44']
[2024-10-06T21:03:45.852+0000] {standard_task_runner.py:105} INFO - Job 247: Subtask obtener_y_preparar_cotizaciones
[2024-10-06T21:03:45.968+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-06T21:03:46.197+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-06T21:03:46.201+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T21:03:46.248+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-06T21:03:46.249+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-06T21:03:46.263+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:46.266+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-06T21:03:47.655+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-06T21:03:47.662+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T21:03:47.663+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-06T21:03:47.671+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-06T21:03:47.684+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-06T21:03:47.770+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-06T21:03:47.770+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-06T21:03:47.770+0000] {multi.py:184} ERROR - ['TGNO4.BA', 'AMZN.BA', 'PAMP.BA', 'AAPL.BA', 'CEPU.BA', 'BBAR.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-06T21:03:47.795+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-06T21:03:47.816+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-06T21:03:47.817+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-06T21:03:49.090+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T21:03:49.102+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T21:03:49.103+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241006T210345, end_date=20241006T210349
[2024-10-06T21:03:49.133+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T21:03:49.154+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T21:03:49.155+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-15T18:15:42.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T18:15:42.616+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-15T18:15:42.652+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-10-15T18:15:42.655+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-15T18:15:42.799+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-09-07 00:00:00+00:00
[2024-10-15T18:15:42.848+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=460) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T18:15:42.853+0000] {standard_task_runner.py:72} INFO - Started process 517 to run task
[2024-10-15T18:15:42.858+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp70q37lpp']
[2024-10-15T18:15:42.898+0000] {standard_task_runner.py:105} INFO - Job 332: Subtask obtener_y_preparar_cotizaciones
[2024-10-15T18:15:43.049+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-09-07T00:00:00+00:00 [running]> on host f03003374728
[2024-10-15T18:15:43.333+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-10-15T18:15:43.349+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T18:15:43.385+0000] {logging_mixin.py:190} INFO - 2024-09-07
[2024-10-15T18:15:43.389+0000] {logging_mixin.py:190} INFO - 2024-09-08
[2024-10-15T18:15:43.407+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:15:43.407+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:15:43.409+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:15:43.410+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:15:43.411+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:15:43.414+0000] {cache.py:336} INFO - Failed to create CookieCache, reason: Error creating CookieCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'. CookieCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2024-10-15T18:15:45.138+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-15T18:15:45.143+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-15T18:15:45.144+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-15T18:15:45.162+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-15T18:15:45.407+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-15T18:15:45.483+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-15T18:15:45.484+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-15T18:15:45.485+0000] {multi.py:184} ERROR - ['BBAR.BA', 'AAPL.BA', 'AMZN.BA', 'CEPU.BA', 'PAMP.BA', 'TGNO4.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-09-07 -> 2024-09-08)')
[2024-10-15T18:15:45.506+0000] {warnings.py:112} WARNING - /opt/***/dags/stocks_prices_daily.py:15: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_data = daily_stock_data.stack(level='Ticker').reset_index()

[2024-10-15T18:15:45.553+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-15T18:15:45.554+0000] {logging_mixin.py:190} INFO - redshift_conn
[2024-10-15T18:15:46.887+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-15T18:15:46.903+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T18:15:46.903+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20241015T181542, end_date=20241015T181546
[2024-10-15T18:15:46.940+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-15T18:15:46.957+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T18:15:46.958+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
