[2024-10-26T16:34:16.646+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:34:16.670+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T16:34:16.687+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T16:34:16.699+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:34:16.817+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T16:34:16.845+0000] {standard_task_runner.py:72} INFO - Started process 835 to run task
[2024-10-26T16:34:16.841+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpk8gw_lu8']
[2024-10-26T16:34:16.861+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:34:16.998+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:34:17.193+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T16:34:17.201+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:34:17.222+0000] {logging_mixin.py:190} INFO - 2024-10-13
[2024-10-26T16:34:17.228+0000] {logging_mixin.py:190} INFO - 2024-10-14
[2024-10-26T16:34:17.914+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:17.933+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T16:34:17.933+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T16:34:17.938+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T16:34:17.939+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T16:34:17.945+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:34:17.946+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T16:34:17.946+0000] {multi.py:184} ERROR - ['AMZN.BA', 'PAMP.BA', 'BBAR.BA', 'TGNO4.BA', 'AAPL.BA', 'CEPU.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-10-13 -> 2024-10-14)')
[2024-10-26T16:34:17.967+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:34:19.350+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:34:19.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:34:19.394+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T163416, end_date=20241026T163419
[2024-10-26T16:34:19.457+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:34:19.484+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:34:19.487+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T16:37:13.322+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:37:13.421+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T16:37:13.473+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T16:37:13.479+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:37:13.588+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T16:37:13.612+0000] {standard_task_runner.py:72} INFO - Started process 1874 to run task
[2024-10-26T16:37:13.633+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpvsed4aq7']
[2024-10-26T16:37:13.670+0000] {standard_task_runner.py:105} INFO - Job 283: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:37:13.844+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:37:14.163+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T16:37:14.202+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:37:14.310+0000] {logging_mixin.py:190} INFO - 2024-10-13
[2024-10-26T16:37:14.331+0000] {logging_mixin.py:190} INFO - 2024-10-14
[2024-10-26T16:37:15.147+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:37:15.148+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:37:15.158+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T16:37:15.166+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T16:37:15.171+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:37:15.171+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:37:15.187+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T16:37:15.188+0000] {multi.py:184} ERROR - ['PAMP.BA', 'TGNO4.BA', 'AMZN.BA', 'CEPU.BA', 'AAPL.BA', 'BBAR.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-10-13 -> 2024-10-14)')
[2024-10-26T16:37:15.264+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:37:16.595+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:37:16.615+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:37:16.616+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T163713, end_date=20241026T163716
[2024-10-26T16:37:16.647+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:37:16.692+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:37:16.694+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T18:55:56.966+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T18:55:56.984+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T18:55:56.991+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T18:55:56.992+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T18:55:57.008+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T18:55:57.015+0000] {standard_task_runner.py:72} INFO - Started process 453 to run task
[2024-10-26T18:55:57.024+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpigupvmso']
[2024-10-26T18:55:57.038+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T18:55:57.174+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host 0c643dd08f0d
[2024-10-26T18:55:57.276+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T18:55:57.279+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T18:55:57.301+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-13 a 2024-10-14
[2024-10-26T18:55:57.311+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:57.326+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T185556, end_date=20241026T185557
[2024-10-26T18:55:57.345+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T18:55:57.346+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'config/config.json'; 453)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:57.392+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T18:55:57.434+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T18:55:57.445+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:04:02.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:04:02.344+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:04:02.359+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:04:02.360+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:04:02.379+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T19:04:02.389+0000] {standard_task_runner.py:72} INFO - Started process 446 to run task
[2024-10-26T19:04:02.404+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpgmeiu84t']
[2024-10-26T19:04:02.407+0000] {standard_task_runner.py:105} INFO - Job 205: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:04:02.501+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host 22d081b4f909
[2024-10-26T19:04:02.624+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T19:04:02.633+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:04:02.646+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-13 a 2024-10-14
[2024-10-26T19:04:02.649+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:04:02.662+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T190402, end_date=20241026T190402
[2024-10-26T19:04:02.675+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:04:02.678+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 205 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 446)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:04:02.712+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:04:02.761+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:04:02.775+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:09:14.530+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:09:14.556+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:09:14.571+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:09:14.577+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:09:14.605+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T19:09:14.621+0000] {standard_task_runner.py:72} INFO - Started process 437 to run task
[2024-10-26T19:09:14.629+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpaoo87jle']
[2024-10-26T19:09:14.633+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:09:14.725+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host f4cb477e9eef
[2024-10-26T19:09:14.830+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T19:09:14.839+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:09:14.856+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-13 a 2024-10-14
[2024-10-26T19:09:14.857+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:09:14.877+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T190914, end_date=20241026T190914
[2024-10-26T19:09:14.894+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:09:14.899+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 89 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 437)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:09:14.946+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:09:15.019+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:09:15.044+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:13:17.764+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:13:17.793+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:13:17.817+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:13:17.818+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:13:17.848+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T19:13:17.866+0000] {standard_task_runner.py:72} INFO - Started process 826 to run task
[2024-10-26T19:13:17.873+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp1oh4prbr']
[2024-10-26T19:13:17.884+0000] {standard_task_runner.py:105} INFO - Job 238: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:13:17.966+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host 2e7a74dc0e24
[2024-10-26T19:13:18.064+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T19:13:18.068+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:13:18.079+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-13 a 2024-10-14
[2024-10-26T19:13:18.084+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:13:18.972+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:18.973+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:18.979+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:18.984+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:19.082+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  5 of 6 completed
[2024-10-26T19:13:19.088+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T19:13:19.091+0000] {multi.py:184} ERROR - ['PAMP.BA', 'AAPL.BA', 'AMZN.BA', 'TGNO4.BA', 'BBAR.BA', 'CEPU.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-10-13 -> 2024-10-14)')
[2024-10-26T19:13:19.082+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  5 of 6 completed
[2024-10-26T19:13:19.167+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:13:19.173+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:13:19.201+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:13:21.525+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:13:21.535+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:13:21.587+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:13:21.593+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:13:21.596+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:13:21.601+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:13:21.704+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:13:21.707+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T191317, end_date=20241026T191321
[2024-10-26T19:13:21.773+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:13:21.848+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:13:21.850+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:16:59.796+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:16:59.808+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:16:59.815+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-26T19:16:59.816+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:16:59.830+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-13 00:00:00+00:00
[2024-10-26T19:16:59.834+0000] {standard_task_runner.py:72} INFO - Started process 792 to run task
[2024-10-26T19:16:59.841+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpiem5k1x4']
[2024-10-26T19:16:59.845+0000] {standard_task_runner.py:105} INFO - Job 401: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:16:59.910+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-13T00:00:00+00:00 [running]> on host 3ba590fe69c6
[2024-10-26T19:16:59.998+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-26T19:17:00.001+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:17:00.018+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-13 a 2024-10-14
[2024-10-26T19:17:00.024+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:17:00.756+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:17:00.759+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:17:00.809+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:17:00.839+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:17:00.891+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:17:00.892+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:17:00.895+0000] {multi.py:171} ERROR - 
6 Failed downloads:
[2024-10-26T19:17:00.898+0000] {multi.py:184} ERROR - ['CEPU.BA', 'PAMP.BA', 'BBAR.BA', 'TGNO4.BA', 'AMZN.BA', 'AAPL.BA']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-10-13 -> 2024-10-14)')
[2024-10-26T19:17:00.916+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:17:00.917+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:17:00.932+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:17:02.273+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:17:02.275+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:17:02.280+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:17:02.280+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:17:02.281+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:17:02.281+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:17:02.356+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:17:02.365+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241026T191659, end_date=20241026T191702
[2024-10-26T19:17:02.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:17:02.527+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
