[2024-10-26T16:34:19.181+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:34:19.209+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T16:34:19.232+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T16:34:19.233+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:34:19.279+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T16:34:19.283+0000] {standard_task_runner.py:72} INFO - Started process 900 to run task
[2024-10-26T16:34:19.288+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpgi8xpan8']
[2024-10-26T16:34:19.295+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:34:19.414+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:34:19.470+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T16:34:19.473+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:34:19.484+0000] {logging_mixin.py:190} INFO - 2024-10-18
[2024-10-26T16:34:19.485+0000] {logging_mixin.py:190} INFO - 2024-10-19
[2024-10-26T16:34:20.286+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:20.260+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:20.299+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:20.301+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:34:20.303+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:34:20.310+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:34:20.407+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:34:22.971+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:34:22.987+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:34:22.987+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T163419, end_date=20241026T163422
[2024-10-26T16:34:23.023+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:34:23.037+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T16:37:18.546+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T16:37:18.575+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T16:37:18.598+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T16:37:18.598+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T16:37:18.846+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T16:37:18.878+0000] {standard_task_runner.py:72} INFO - Started process 1977 to run task
[2024-10-26T16:37:18.897+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpprme_h82']
[2024-10-26T16:37:18.921+0000] {standard_task_runner.py:105} INFO - Job 301: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T16:37:19.122+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host 99ce4a540f58
[2024-10-26T16:37:19.386+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T16:37:19.391+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T16:37:19.438+0000] {logging_mixin.py:190} INFO - 2024-10-18
[2024-10-26T16:37:19.439+0000] {logging_mixin.py:190} INFO - 2024-10-19
[2024-10-26T16:37:20.434+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T16:37:20.444+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T16:37:20.445+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T16:37:20.449+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T16:37:20.464+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T16:37:20.472+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T16:37:20.485+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T16:37:22.646+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T16:37:22.660+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T16:37:22.661+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T163718, end_date=20241026T163722
[2024-10-26T16:37:22.713+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T16:37:22.747+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T16:37:22.750+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T18:55:59.009+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T18:55:59.037+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T18:55:59.051+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T18:55:59.052+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T18:55:59.105+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T18:55:59.117+0000] {standard_task_runner.py:72} INFO - Started process 493 to run task
[2024-10-26T18:55:59.121+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpcw9rlpt5']
[2024-10-26T18:55:59.125+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T18:55:59.181+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host 0c643dd08f0d
[2024-10-26T18:55:59.277+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T18:55:59.289+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T18:55:59.309+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-18 a 2024-10-19
[2024-10-26T18:55:59.312+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:59.329+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T185559, end_date=20241026T185559
[2024-10-26T18:55:59.347+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T18:55:59.348+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 101 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: 'config/config.json'; 493)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
[2024-10-26T18:55:59.390+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T18:55:59.429+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T18:55:59.439+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:04:04.816+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:04:04.848+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:04:04.871+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:04:04.873+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:04:04.899+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T19:04:04.925+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpctjo0dwt']
[2024-10-26T19:04:04.919+0000] {standard_task_runner.py:72} INFO - Started process 488 to run task
[2024-10-26T19:04:04.932+0000] {standard_task_runner.py:105} INFO - Job 215: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:04:05.036+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host 22d081b4f909
[2024-10-26T19:04:05.157+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T19:04:05.162+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:04:05.187+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-18 a 2024-10-19
[2024-10-26T19:04:05.191+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:04:05.214+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T190404, end_date=20241026T190405
[2024-10-26T19:04:05.235+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:04:05.237+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 215 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 488)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:04:05.285+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:04:05.310+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:04:05.313+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:09:17.681+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:09:17.691+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:09:17.699+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:09:17.700+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:09:17.708+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T19:09:17.712+0000] {standard_task_runner.py:72} INFO - Started process 473 to run task
[2024-10-26T19:09:17.716+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmp606_s3pw']
[2024-10-26T19:09:17.719+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:09:17.751+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host f4cb477e9eef
[2024-10-26T19:09:17.794+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T19:09:17.795+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:09:17.803+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-18 a 2024-10-19
[2024-10-26T19:09:17.804+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:09:17.809+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T190917, end_date=20241026T190917
[2024-10-26T19:09:17.815+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:09:17.816+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 100 for task obtener_y_preparar_cotizaciones ([Errno 2] No such file or directory: '/opt/airflow/config/config.json'; 473)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/functions/main_tasks.py", line 29, in stocks_to_redshift
    with open('/opt/airflow/config/config.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/config/config.json'
[2024-10-26T19:09:17.858+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T19:09:17.872+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:09:17.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:13:30.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:13:30.197+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:13:30.233+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:13:30.254+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:13:30.338+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T19:13:30.355+0000] {standard_task_runner.py:72} INFO - Started process 955 to run task
[2024-10-26T19:13:30.375+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpqjy21uts']
[2024-10-26T19:13:30.391+0000] {standard_task_runner.py:105} INFO - Job 261: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:13:30.493+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host 2e7a74dc0e24
[2024-10-26T19:13:30.633+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T19:13:30.645+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:13:30.695+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-18 a 2024-10-19
[2024-10-26T19:13:30.722+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:13:31.549+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:13:31.555+0000] {logging_mixin.py:190} WARNING - [****************      33%                       ]  2 of 6 completed
[2024-10-26T19:13:31.616+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:13:31.647+0000] {logging_mixin.py:190} WARNING - [**********************67%*******                ]  4 of 6 completed
[2024-10-26T19:13:31.740+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:13:31.740+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:13:31.764+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:13:31.769+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:13:31.817+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:13:33.199+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:13:33.203+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:13:33.909+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:13:33.921+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:13:33.937+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:13:33.944+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:13:34.160+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:13:34.163+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T191330, end_date=20241026T191334
[2024-10-26T19:13:34.323+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:13:34.370+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-26T19:17:03.121+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T19:17:03.145+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:17:03.192+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-10-26T19:17:03.196+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-26T19:17:03.215+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): obtener_y_preparar_cotizaciones> on 2024-10-18 00:00:00+00:00
[2024-10-26T19:17:03.236+0000] {standard_task_runner.py:72} INFO - Started process 874 to run task
[2024-10-26T19:17:03.254+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_cargar_cotizaciones', 'obtener_y_preparar_cotizaciones', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '412', '--raw', '--subdir', 'DAGS_FOLDER/dag_cargar_cotizaciones.py', '--cfg-path', '/tmp/tmpq771sfo2']
[2024-10-26T19:17:03.272+0000] {standard_task_runner.py:105} INFO - Job 412: Subtask obtener_y_preparar_cotizaciones
[2024-10-26T19:17:03.377+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_cargar_cotizaciones.obtener_y_preparar_cotizaciones scheduled__2024-10-18T00:00:00+00:00 [running]> on host 3ba590fe69c6
[2024-10-26T19:17:03.538+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_cargar_cotizaciones' AIRFLOW_CTX_TASK_ID='obtener_y_preparar_cotizaciones' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-10-26T19:17:03.540+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T19:17:03.569+0000] {main_tasks.py:27} INFO - Proceso iniciado para el rango de fechas: 2024-10-18 a 2024-10-19
[2024-10-26T19:17:03.573+0000] {main_tasks.py:34} INFO - Tickers cargados desde el archivo de configuración: ['BBAR.BA', 'CEPU.BA', 'AAPL.BA', 'TGNO4.BA', 'PAMP.BA', 'AMZN.BA']
[2024-10-26T19:17:04.302+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:17:04.308+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2024-10-26T19:17:04.360+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:17:04.365+0000] {logging_mixin.py:190} WARNING - [**********************50%                       ]  3 of 6 completed
[2024-10-26T19:17:04.613+0000] {logging_mixin.py:190} WARNING - [**********************83%***************        ]  5 of 6 completed
[2024-10-26T19:17:04.614+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  6 of 6 completed
[2024-10-26T19:17:04.634+0000] {main_tasks.py:38} INFO - Cargando datos de 6 tickers en la tabla pda."2024_felipe_miguel_reto_schema".stocks_prices_daily
[2024-10-26T19:17:04.634+0000] {redshift_operations.py:19} INFO - Estableciendo conexión con Redshift.
[2024-10-26T19:17:04.641+0000] {base.py:84} INFO - Retrieving connection 'redshift_conn'
[2024-10-26T19:17:05.971+0000] {redshift_operations.py:28} INFO - Conexión con Redshift establecida. Ejecutando función.
[2024-10-26T19:17:05.972+0000] {redshift_operations.py:45} INFO - Iniciando carga de datos en Redshift.
[2024-10-26T19:17:06.941+0000] {redshift_operations.py:53} INFO - Carga de datos completada exitosamente.
[2024-10-26T19:17:06.945+0000] {redshift_operations.py:31} INFO - Conexión con Redshift cerrada.
[2024-10-26T19:17:06.949+0000] {main_tasks.py:41} INFO - Proceso finalizado exitosamente.
[2024-10-26T19:17:06.950+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-26T19:17:06.969+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T19:17:06.970+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_cargar_cotizaciones, task_id=obtener_y_preparar_cotizaciones, run_id=scheduled__2024-10-18T00:00:00+00:00, execution_date=20241018T000000, start_date=20241026T191703, end_date=20241026T191706
[2024-10-26T19:17:07.044+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-26T19:17:07.097+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T19:17:07.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
